# This configuration is for development only!
# If you're looking for an example configuration, take a look at the sample_config.yml.

loglevel: debug
server:
  host: localhost:8080
  write_timeout: 5
  read_timeout: 5
  tls: false
  cert: path to ssl certificate
  private_key: path to ssl private key
auth:
  public_key_path: secrets/token.public
  private_key_path: secrets/token.private
  admin_password: admin
  moderator_password: mod
  read_only_password: ro
cors:
  origins: "*"
  loglevel: info
